### ISSUE TITLE
How to convert ssd.caffemodel to mxnet_ssd.params?

### ISSUE THREAD

**Issue by gezhiwei** [zhreshold/mxnet-ssd#29]
For example, I have the VGG_VOC0712_SSD_300x300_iter_60000.caffemodel, and I want to get the same ssd_300-symbol.json and ssd_300-0000.params, would you show me how can I convert the ssd.caffemodel to mxnet_ssd.params and mxnet_ssd-symbol.json? Thank you.

**Comment by zhreshold** [comment]
There are several non-official caffe layers in ssd, some are not even versatile, so the mxnet converter won't recognize the caffemodel. I have not plan to modify the converter because I still can't find an elegant way to construct a network from caffemodel cause some parameters must be manually set before that, in other words, convert prototxt to .json is a bit tricky. That why the network has to be designed prior to that.

However, convert caffemodel to .params is way easier, convert convolutional layers is written in converter, all you have to do is to find the Normalize layer and grab the scaling parameters. All these operations could be done in python with numpy and protobuf, mxnet use arg_params and aux_params simply as dicts. 

Feel free to submit a PR if you find better ways.

**Comment by gezhiwei** [comment]
thank you, I will try it ^-^
